fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

security.login:
    path: /admin/login
    defaults: { _controller: AppBundle:Security:login }
security.login_check:
    path: /admin/login_check
security.logout:
    path: /admin/logout

admin.index:
    path: /admin
    defaults: { _controller: AppBundle:Admin:index }

home.index:
    path: /
    defaults: { _controller: AppBundle:Home:index }
