<?php

namespace AppBundle\Entity;

/**
 * EntryEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
