<?php

namespace AppBundle\Entity;

/**
 * EntryPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryPhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
