<?php

namespace AppBundle\Entity;

/**
 * EntryAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
